### ISSUE TITLE
Ubuntu 20.04 Launcher error - cannot load such file

### ISSUE THREAD

**Issue by hchesser** [OpenSatKit/OpenSatKit#114]
Hello,

I have installed Ubuntu 20.04 (I have not installed Virtualbox as described in your video).  I download and installed the tar file - there was a warning about ruby 2.5.8 (no longer supported).  There was also an error that Cosmos now needs ruby => than 2.6.

At the end of the install I ran 'ruby Launcher' from the cosmos directory and get the message:

Traceback (most recent call last):
	3: from Launcher:13:in `<main>'
	2: from /home/hugh/OpenSatKit-master/cosmos/tools/tool_launch.rb:14:in `tool_launch'
	1: from /home/hugh/.rbenv/versions/2.5.8/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/home/hugh/.rbenv/versions/2.5.8/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler/setup (LoadError)

I have tried upgrading ruby using the rbenv command to 3.2.2, but I get the same error.

**Comment by junfuture1103** [comment]
I have a same problem

Traceback (most recent call last):
	3: from Launcher:13:in `<main>'
	2: from /home/jun20/jun/kaist_research/OpenSatKit-master/cosmos/tools/tool_launch.rb:16:in `tool_launch'
	1: from Launcher:14:in `block in <main>'
Launcher:14:in `require': cannot load such file -- cosmos/tools/launcher/launcher (LoadError)
