### ISSUE TITLE
 ruby Launcher  libqtruby4shared.so : cannot open 

### ISSUE THREAD

**Issue by cjhien** [OpenSatKit/OpenSatKit#117]
ruby Launcher
2024/01/08 06:34:41.952  FATAL: Fatal Exception! Exiting...
2024/01/08 06:34:41.952  FATAL: LoadError : libqtruby4shared.so.2: cannot open shared object file: No such file or directory - /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.5/lib/2.5/qtruby4.so
/var/lib/gems/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt4.rb:25:in `require'
/var/lib/gems/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt4.rb:25:in `<top (required)>'
/var/lib/gems/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt.rb:1:in `require'
/var/lib/gems/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt.rb:1:in `<top (required)>'
/var/lib/gems/2.5.0/gems/cosmos-4.5.2/lib/cosmos/gui/qt.rb:80:in `require'
/var/lib/gems/2.5.0/gems/cosmos-4.5.2/lib/cosmos/gui/qt.rb:80:in `<top (required)>'
/var/lib/gems/2.5.0/gems/cosmos-4.5.2/lib/cosmos/gui/qt_tool.rb:12:in `require'
/var/lib/gems/2.5.0/gems/cosmos-4.5.2/lib/cosmos/gui/qt_tool.rb:12:in `<top (required)>'
/var/lib/gems/2.5.0/gems/cosmos-4.5.2/lib/cosmos/tools/launcher/launcher.rb:13:in `require'
/var/lib/gems/2.5.0/gems/cosmos-4.5.2/lib/cosmos/tools/launcher/launcher.rb:13:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/cosmos-4.5.2/lib/cosmos/top_level.rb:556:in `catch_fatal_exception'
/var/lib/gems/2.5.0/gems/cosmos-4.5.2/lib/cosmos/tools/launcher/launcher.rb:12:in `<top (required)>'
Launcher:14:in `require'
Launcher:14:in `block in <main>'
/home/cjhien/OpenSatKit-master/cosmos/tools/tool_launch.rb:16:in `tool_launch'
Launcher:13:in `<main>'

**Comment by luoflyxidian** [comment]
sudo gem install qtbindings
